## 1.8 Linear Algebra Refresher

## Notes

### Linear Algebra Refresher
* Vector operations
* Multiplication
  * Vector-vector multiplication
  * Matrix-vector multiplication
  * Matrix-matrix multiplication
* Identity matrix
* Inverse

### Vector operations

![](imgs/ml-1-8/1.png)
![](imgs/ml-1-8/2.png)

In [1]:
import numpy as np

In [9]:
u = np.array([2, 7, 5, 6])
print(u)
v = np.array([3, 4, 8, 6])
print(v)

# addition 
u + v
print(u + v)

# subtraction 
u - v
print(u - v)

# scalar multiplication 
2 * v
print(2 * v)

[2 7 5 6]
[3 4 8 6]
[ 5 11 13 12]
[-1  3 -3  0]
[ 6  8 16 12]


### Multiplication

#####  Vector-vector multiplication

![](imgs/ml-1-8/3.png)
![](imgs/ml-1-8/4.png)

In [3]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [14]:
vector_vector_multiplication(u, v)

np.float64(110.0)

In [15]:
u.dot(v)

np.int64(110)

#####  Matrix-vector multiplication

![](imgs/ml-1-8/5.png)
![](imgs/ml-1-8/6.png)

In [ ]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [17]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [20]:
U.shape

(3, 4)

In [18]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [21]:
matrix_vector_multiplication(U, v)

array([98., 31., 35.])

In [22]:
U.dot(v)

array([98, 31, 35])

#####  Matrix-matrix multiplication

![](imgs/ml-1-8/7.png)

In [32]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [33]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [34]:
V.shape

(4, 3)

In [35]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [36]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [37]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity matrix

![](imgs/ml-1-8/7.png)

In [ ]:
I = np.eye(3)

In [38]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Inverse
![](imgs/ml-1-8/8.png)

In [39]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)

In [40]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [41]:
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])