## 1.7 Introduction to NumPy

# Understanding Numpy: A Simple Introduction

Numpy, short for Numerical Python, is a powerful Python library that enables efficient and convenient array manipulation and mathematical operations. It forms the foundation for many scientific and data-related tasks. In this article, we'll provide a straightforward explanation of Numpy concepts and how to use them.

## Importing Numpy

Before diving into Numpy's capabilities, we need to import it. Conventionally, we import Numpy with the alias `np`, making it easier to reference its functions:

In [1]:
import numpy as np

## Creating Arrays

Arrays are the building blocks of Numpy, and they can be thought of as lists but with enhanced features.

### Creating Arrays with Zeros, Ones, or Constants

You can create arrays filled with zeros, ones, or any constant using `np.zeros()`, `np.ones()`, and `np.full()`:

In [5]:
zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
constant_array = np.full(10, 3)
print(constant_array)

[3 3 3 3 3 3 3 3 3 3]


### Converting Lists to Arrays

To convert a Python list into a Numpy array, you can use `np.array()`:

In [12]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)
print(array_from_list)

[2 3 4]


### Generating Ranges of Numbers

Numpy provides functions for generating arrays of sequential numbers. For example:

In [13]:
range_array = np.arange(10)  # Creates an array from 0 to 9
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


### Creating Arrays with Linear Spacing

`np.linspace()` creates arrays with evenly spaced numbers within a specified range:

In [14]:
linspace_array = np.linspace(0, 1, 11)  # Creates 11 numbers from 0 to 1
print(linspace_array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Multi-dimensional Arrays

Numpy can handle multi-dimensional arrays, often referred to as matrices. Here are some examples:

In [15]:
zeros_matrix = np.zeros((5, 2))
print(zeros_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
ones_matrix = np.ones((5, 2))
print(ones_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
constant_matrix = np.full((5, 2), 3)
print(constant_matrix)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


## Indexing and Slicing Arrays

Like Python lists, you can access elements in Numpy arrays using indexing and slicing. For two-dimensional arrays:

In [18]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
print(arr)

[[2 3 4]
 [4 5 6]]


In [19]:
first_row = arr[0]      # Gets the first row
print(first_row)

[2 3 4]


In [20]:
first_col = arr[:, 0]  # Gets the first column
print(first_col)

[2 4]


## Generating Random Arrays

Numpy can create arrays filled with random numbers. To ensure reproducibility, you can set a seed using `np.random.seed()`:

In [21]:
np.random.seed(2)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1
print(random_array)

[[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]


For random numbers from a normal distribution or integers within a range:

In [22]:
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))
print(random_integers)

[[83 31]
 [66 80]
 [52 76]
 [50  4]
 [90 63]]


## Array Operations

Numpy excels in performing mathematical operations on arrays efficiently.

### Element-wise Operations

You can perform operations on entire arrays element by element:

In [24]:
print(arr)
arr = arr + 1   # Adds 1 to each element
print(arr)
arr = arr * 2   # Multiplies each element by 2
print(arr)
# Similar operations for division and exponentiation

[[ 6  8 10]
 [10 12 14]]
[[ 7  9 11]
 [11 13 15]]
[[14 18 22]
 [22 26 30]]


### Element-wise Operations with Two Arrays

You can also perform operations between two arrays of the same shape:

In [25]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result = arr1 + arr2  # Element-wise addition
result = arr1 / arr2  # Element-wise division


### Comparison Operations

You can perform element-wise comparisons and create boolean arrays:

In [27]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]
print(greater_than_2)

[False False  True  True]


### Selecting Elements Based on Conditions

You can create subarrays based on certain conditions:

In [28]:
selected_elements = arr[arr > 1]  # Gets elements greater than 1

## Summary Operations

Numpy provides functions for summarizing array data:

In [30]:
min_value = arr.min()    # Minimum value
print(min_value)
max_value = arr.max()    # Maximum value
print(max_value)
sum_value = arr.sum()    # Sum of all elements
print(sum_value)
mean_value = arr.mean()  # Mean (average) value
print(mean_value)
std_deviation = arr.std()  # Standard deviation
print(std_deviation)

1
4
10
2.5
1.118033988749895
